[project]
name = "rag-plus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy-ai>=2.6.27",
    "ipykernel>=6.29.5",
    "numpy>=2.3.0",
]
